version: "3.9"
services:
  web:
    build:
      context: .
      target: development
    env_file: env
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
  redis:
    image: "redis"
    hostname: "${REDIS_HOST}"
    command: --port ${REDIS_PORT}
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
  start_dependencies:
    image: alpine:latest
    depends_on:
      - redis
      - web
    command: >
      /bin/sh -c "
        apk update && apk add netcat-openbsd;
        while ! nc -z web ${PROXY_PORT};
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
        ping -c1 web;
      "
  tests:
    build:
      context: .
      target: systemtest
    env_file: env
    depends_on:
      - redis
      - web
